Update molecule
Ansible Molecule stopped working. Turned out that molecule-docker was
moved to molecule-plugins, see: https://github.com/ansible-community/molecule-plugins

The latest ansible-lint version breaks molecule because it they have
different ansible-compat version dependencies
molecule depends on ansible-compat 3.0.2 whereas the latest ansible-lint
version depends on ansible-compat>=4.0.5::

  Installing collected packages: ansible-compat, molecule
    Attempting uninstall: ansible-compat
      Found existing installation: ansible-compat 4.1.2
      Uninstalling ansible-compat-4.1.2:
        Successfully uninstalled ansible-compat-4.1.2
    Attempting uninstall: molecule
      Found existing installation: molecule 5.0.0
      Uninstalling molecule-5.0.0:
        Successfully uninstalled molecule-5.0.0
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  ansible-lint 6.17.2 requires ansible-compat>=4.0.5, but you have ansible-compat 3.0.2 which is incompatible.
  Successfully installed ansible-compat-3.0.2 molecule-5.0.1

ansible-lint 6.16.2 has no ansible-compat dependency.

  ❯ molecule --version
  molecule 5.0.1 using python 3.9
      ansible:2.15.1
      azure:23.4.1 from molecule_plugins
      containers:23.4.1 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
      delegated:5.0.1 from molecule
      docker:23.4.1 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
      ec2:23.4.1 from molecule_plugins
      gce:23.4.1 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
      podman:23.4.1 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
      vagrant:23.4.1 from molecule_plugins

  ❯ ansible --version
  ansible [core 2.15.1]
    config file = /home/jkirk/.ansible.cfg
    configured module search path = ['/home/jkirk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    ansible python module location = /home/jkirk/projects/misc/ansible-role-base/venv/lib/python3.9/site-packages/ansible
    ansible collection location = /home/jkirk/.ansible/collections:/usr/share/ansible/collections
    executable location = /home/jkirk/projects/misc/ansible-role-base/venv/bin/ansible
    python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/jkirk/projects/misc/ansible-role-base/venv/bin/python3)
    jinja version = 3.1.2
    libyaml = True