Fix Workflow Ansible Molecule
The following error message is shown in the logs:

  Run actions/setup-python@v4
  Installed versions
    Version 3.9.2 was not found in the local cache
    Error: The version '3.9.2' with architecture 'x64' was not found for Ubuntu 22.04.
    The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

This is because the ubuntu-latest currently uses the Ubuntu 22.04 runner
image, see: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners

But python 3.9.2 is not available on Ubuntu 22.04, see:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

As we still run Debian/bullseye, changed the runner to Ubuntu 20.04 to
match the Python version of Debian.

FTR, Debian/bookworm comes with Python 3.11.2 which is available in
Ubuntu 22.04